name:  wsifir-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - simpleitk
  - scikit-image
  - scipy
  - dask
  - ipykernel
  - pip
  - pip:
      - git+https://github.com/AstroPathJHU/sidus.git
      - antspyx
      - pyimagej
      - ipywidgets