name: environment.yml  
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - pandas
  - ants
  - scikit-learn
  - simpleitk
  - scikit-image
  - seaborn
  - scipy
  - dask
  - pip
  - pip:
      - git+https://github.com/AstroPathJHU/sidus.git