name:  wsifir-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - simpleitk
  - scikit-image
  - scipy
  - dask
  - ipykernel
  - pyimagej
  - ipywidgets
  - pip
  - pip:
      - git+https://github.com/AstroPathJHU/sidus.git
      - antspyx
